# IMPROVEMENTS NEEDED:
# - Properly fix the used actions tags.
# - Properly tag the builds.

name: CI - Lint, Build, Test & Security Check.

on:
  push:
    branches:
      - dev

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      # Required when publishing results (badge / API / code scanning)
      security-events: write
      id-token: write
      # Recommended reads for private repos to avoid GraphQL/SAST gaps
      contents: read
      issues: read
      pull-requests: read
      checks: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Run OSSF Scorecard
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  # i decided to mantain this job here just to be explicit on how the workflow works. It probably will become an composable action and i know that it's not a best practice build an job just to generate cache. I could do it in the code-lint job and retrieve in the subsequent ones.
  create-cache:
    runs-on: ubuntu-latest
    steps:
      # These 4 steps will become an composable action soon.
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22.20
          cache: npm

      - name: Cache Dependencies
        uses: actions/cache/save@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-node-

      - name: Install dependencies
        run: npm ci

  code-lint:
    name: Code lint
    runs-on: ubuntu-latest
    needs: create-cache
    steps:
      # These 4 steps will become an composable action soon.
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22.20
          cache: npm

      - name: Cache Dependencies
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: code-lint
    steps:
      # These 4 steps will become an composable action soon.
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          node-version: 22.20
          cache: npm

      - name: Cache Dependencies
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{runner.os}}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

  docker-build:
    name: Lint and build Docker image.
    runs-on: ubuntu-latest
    needs: [code-lint, run-unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: hivebox:latest
          target: prod
          # Export as oci format for a lower image size.
          outputs: type=oci, dest=/tmp/hivebox.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hivebox-image
          path: /tmp/hivebox.tar

  # will test the endpoint on docker.
  endpoint-test:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: hivebox-image
          path: /tmp

      - name: Load Docker image.
        run: docker load -i /tmp/hivebox.tar

      - name: Run container
        run: |
          docker run -d --name hivebox-latest -p 3000:3000 hivebox:latest
          sleep 10

      - name: Test endpoint
        run: |
          response=$(curl http://localhost:3000/version)
          if [[ $response != "0.0.2" ]]; then exit 1; fi
