name: CI - Lint, Build, Test & Security Check.

on:
  push:
    branches:
      - dev

jobs:
  ci:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: lint dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22.20

      - name: Install dependencies
        run: npm ci

      - name: lint code
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

      - name: unit tests
        run: npm test

      - name: Endpoint test
        run: |
          npm run dev &
          SERVER_PID=$!
          npx wait-on http://localhost:3000/version -t 30000
          response=$(curl http://localhost:3000/version)
          if [[ $response == "0.0.2" ]]; then
            echo "response valid"
            exit 0
          else
            echo "response invalid"
            exit 1
          fi
          kill $SERVER_PID
